<?php

/**
 * This is the model base class for the table "article".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Article".
 *
 * Columns in table "article" available as properties of the model,
 * followed by relations of table "article" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $content
 * @property string $create_at
 * @property string $create_by
 * @property string $update_at
 * @property string $update_by
 *
 * @property User $updateBy
 * @property User $createBy
 * @property ArticleTag[] $articleTags
 */
abstract class BaseArticle extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'article';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Article|Articles', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('create_at, create_by', 'required'),
			array('name', 'length', 'max'=>255),
			array('create_by, update_by', 'length', 'max'=>11),
			array('content, update_at', 'safe'),
			array('name, content, update_at, update_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, content, create_at, create_by, update_at, update_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'updateBy' => array(self::BELONGS_TO, 'User', 'update_by'),
			'createBy' => array(self::BELONGS_TO, 'User', 'create_by'),
			'articleTags' => array(self::HAS_MANY, 'ArticleTag', 'article_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'content' => Yii::t('app', 'Content'),
			'create_at' => Yii::t('app', 'Create At'),
			'create_by' => null,
			'update_at' => Yii::t('app', 'Update At'),
			'update_by' => null,
			'updateBy' => null,
			'createBy' => null,
			'articleTags' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('create_at', $this->create_at, true);
		$criteria->compare('create_by', $this->create_by);
		$criteria->compare('update_at', $this->update_at, true);
		$criteria->compare('update_by', $this->update_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}