<?php

/**
 * This is the model base class for the table "article_tag".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ArticleTag".
 *
 * Columns in table "article_tag" available as properties of the model,
 * followed by relations of table "article_tag" available as properties of the model.
 *
 * @property string $id
 * @property string $article_id
 * @property string $tag_id
 *
 * @property Tag $tag
 * @property Article $article
 */
abstract class BaseArticleTag extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'article_tag';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ArticleTag|ArticleTags', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('article_id, tag_id', 'required'),
			array('article_id, tag_id', 'length', 'max'=>11),
			array('id, article_id, tag_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tag' => array(self::BELONGS_TO, 'Tag', 'tag_id'),
			'article' => array(self::BELONGS_TO, 'Article', 'article_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'article_id' => null,
			'tag_id' => null,
			'tag' => null,
			'article' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('article_id', $this->article_id);
		$criteria->compare('tag_id', $this->tag_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}