<?php

/**
 * This is the model base class for the table "article".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Article".
 *
 * Columns in table "article" available as properties of the model,
 * followed by relations of table "article" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $content
 * @property string $create_time
 * @property string $create_by
 * @property string $update_time
 * @property string $update_by
 * @property string $delete_time
 * @property integer $delete_by
 *
 * @property User $createBy
 * @property User $updateBy
 * @property ArticleTag[] $articleTags
 */
abstract class BaseArticle extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'article';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Article|Articles', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('create_time, create_by', 'required'),
			array('delete_by', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('create_by, update_by', 'length', 'max'=>11),
			array('content, update_time, delete_time', 'safe'),
			array('name, content, update_time, update_by, delete_time, delete_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, content, create_time, create_by, update_time, update_by, delete_time, delete_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createBy' => array(self::BELONGS_TO, 'User', 'create_by'),
			'updateBy' => array(self::BELONGS_TO, 'User', 'update_by'),
			'articleTags' => array(self::HAS_MANY, 'ArticleTag', 'article_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'content' => Yii::t('app', 'Content'),
			'create_time' => Yii::t('app', 'Create Time'),
			'create_by' => null,
			'update_time' => Yii::t('app', 'Update Time'),
			'update_by' => null,
			'delete_time' => Yii::t('app', 'Delete Time'),
			'delete_by' => Yii::t('app', 'Delete By'),
			'createBy' => null,
			'updateBy' => null,
			'articleTags' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('create_by', $this->create_by);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('update_by', $this->update_by);
		$criteria->compare('delete_time', $this->delete_time, true);
		$criteria->compare('delete_by', $this->delete_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}